/**
 * Client-faithful differential VDOM harness (#1678).
 *
 * For each committed fixture (generated by scripts/gen_vdom_diff_fixtures.py):
 * build a jsdom DOM from the egress-stripped mount HTML, then for each step
 * apply the REAL server patch batch via the REAL client.js applyPatches, and
 * assert the resulting DOM is STRUCTURALLY EQUAL — significant-child tree
 * including dj-if marker placement — to a fresh server render of that state.
 *
 * This closes the gap that let #1408 and #1678 through: the older repro
 * (tab_switch_real_repro.test.js) compared only dj-id *sets* and ignored
 * comment markers, so a misplaced dj-if marker (the #1678 MoveSubtree drift)
 * passed straight through. Here a marker landing one slot off changes the
 * sibling sequence and fails the deep-equal.
 */

import { describe, it, expect } from 'vitest';
import fs from 'fs';
import { createHarnessDom, normalizeSignificantTree } from './_significant_tree.js';

const FIXTURES = ['vdom_diff_kanban_tabs_1678.json'];

for (const file of FIXTURES) {
    const fx = JSON.parse(fs.readFileSync(`./tests/js/fixtures/${file}`, 'utf-8'));

    describe(`client-faithful diff: ${fx.scenario}`, () => {
        it('client DOM matches a fresh server render after every step', async () => {
            const { window, logs } = createHarnessDom(fx.initial_html);
            const { document } = window;
            const sel = fx.root_selector;

            expect(document.querySelector(sel), 'root present in initial_html').toBeTruthy();

            for (let i = 0; i < fx.steps.length; i++) {
                const step = fx.steps[i];

                const rootEl = document.querySelector(sel);
                await window.djust.applyPatches(step.patches, rootEl);

                const actual = normalizeSignificantTree(document.querySelector(sel), window);

                const tmp = document.createElement('div');
                tmp.innerHTML = step.expected_html;
                const expected = normalizeSignificantTree(tmp.querySelector(sel), window);

                expect(
                    actual,
                    `step ${i + 1} [${step.label}]: client DOM significant-child tree ` +
                    `must equal a fresh render of this state`
                ).toEqual(expected);
            }

            const issues = logs.filter(([lvl]) => lvl === 'warn' || lvl === 'error');
            expect(
                issues.map(([lvl, msg]) => `${lvl}: ${msg}`),
                'patcher emitted no warnings/errors'
            ).toEqual([]);
        });
    });
}
